### ISSUE TITLE
CONTRIBUTING.rst references 'stackhut-tool' instead of 'stackhut-common'

### ISSUE THREAD

**Issue by collingreen** [StackHut/stackhut-common#2]
TODO:
- [ ] update to match current project
- [ ] verify steps and tools fully work

**Comment by mands** [comment]
Yes! Absolutely need to updating contributing process - we're all about those PRs :) Will work on this week...

**Comment by mands** [comment]
This issue was moved to StackHut/stackhut-toolkit#13
